const ProjectsArray = [
  {image_path: '/images/projects/lto-network.jpg', thumbnail_path: '/images/projects/thumbnails/lto-network.jpg', tags: ['MongoDB, Express.js, React.js, Node.js'], title: 'LTO Network Homepage', description: 'LTO Network is one of the largest blockchain technology companies in Europe. In conjunction with JBox Creative, the new homepage for their website, ltonetwork.com, was created using a React.js template, with custom components tailored specifically for the client.', projectUrl: 'https://ltonetwork.com'},
    {image_path: '/images/projects/WordPress-logo.png', thumbnail_path: '/images/projects/thumbnails/WordPress-logo.png', tags: ['MongoDB, Express.js, React.js, Node.js'], title:"Custom WordPress API for Enterprise-Level Company", description: "Custom API function for property rental company. Client requested a way to automate changes to their website's list of properties daily. Worked with client's property management company to create API endpoint that loops through JSON data, parsing it into client's property object data structure, syncing website content with data source daily."},

    {image_path: '/images/projects/urban-area-info-finder.jpg', thumbnail_path: '/images/projects/thumbnails/urban-area-info-finder.jpg', tags: ['JavaScript, Google Maps API, Teleport API'], title: 'Urban Area Info Finder', description: 'This project uses the Google Maps API to show a user a map of the world and prompts them to click on a city, obtaining its coordinates. AJAX requests are sent to the Teleport API to retrieve information about the city. Image-Charts API is used to graph the information.', projectUrl: 'https://willmidgette.com/explore-a-city', githubUrl: 'https://github.com/wamidgette/explore-cities'},

    {image_path: '/images/projects/daredevil-dave.jpg', thumbnail_path: '/images/projects/thumbnails/daredevil-dave.jpg', tags: ['CSS, JavaScript'], title: 'Daredevil Dave', description: 'Shoot Daredevil Dave out of the cannon and through the hoop with the spacebar. This game uses CSS animations triggered by JavaScript event listeners and features a score tracker and countdown.', projectUrl: 'https://willmidgette.com/daredevil-dave',githubUrl: 'https://github.com/wamidgette/DaredevilDave' },

    {image_path: '/images/projects/nodejs.jpg', thumbnail_path: '/images/projects/thumbnails/nodejs.jpg', tags: ['Node.js, Express.js'], title: 'Node.js API Coding Challenge', description: 'This is a coding challenge I completed using Node and Express. The purpose was to create a queryable API that called upon an external API and rearranged the data returned based on the queries given by the user. Caching is utilized to improve performance.', githubUrl: 'https://github.com/wamidgette/nodeApiCodingChallenge'}, 

    {image_path: '/images/projects/motorcycle-trips.jpg', thumbnail_path: '/images/projects/thumbnails/motorcycle-trips.jpg', tags: ['MongoDB, Express.js, React.js, Node.js'], title: 'Motorcycle Trips React App', description: 'A web application with CRUD functionality. Motorcycle riders can browse through and sign up for trips with other riders. Admin users can create, update and delete trips, riders, events as they choose. Express.js used to interact with MongoDB database. React.js makes requests to API endpoints on Node.js server to render data.', githubUrl: 'https://github.com/wamidgette/MotorcycleRidersMERNApp'}
  ]

  export default ProjectsArray