const ProjectsArray = [
    {image_path: '/images/projects/daredevil-dave.jpg', thumbnail_path: '/images/projects/thumbnails/daredevil-dave.jpg', tags: ['CSS, JavaScript'], title: 'Daredevil Dave', description: 'Shoot Daredevil Dave out of the cannon and through the hoop with the spacebar. This game uses CSS animations triggered by JavaScript event listeners and features a score tracker and countdown.', projectUrl: './', githubUrl: 'https://github.com/wamidgette/DaredevilDave' },

    {image_path: '/images/projects/urban-area-info-finder.jpg', thumbnail_path: '/images/projects/thumbnails/urban-area-info-finder.jpg', tags: ['JavaScript, Google Maps API, Teleport API'], title: 'Urban Area Info Finder', description: 'This project uses the Google Maps API to show a user a map of the world and prompts them to click on a city, obtaining its coordinates. AJAX requests are sent to the Teleport API to retrieve information about the city. Image-Charts API is used to graph the information.', projectUrl: './', githubUrl: 'https://github.com/wamidgette/UrbanAreaInfoFinder'},

    {image_path: '/images/projects/nodejs.jpg', thumbnail_path: '/images/projects/thumbnails/nodejs.jpg', tags: ['Node.js, Express.js'], title: 'Node.js API Coding Challenge', description: 'This is a coding challenge I completed using Node and Express. The purpose was to create a queryable API that called upon an external API and rearranged the data returned based on the queries given by the user. Caching is utilized to improve performance.', projectUrl: './', githubUrl: 'https://github.com/wamidgette/nodeApiCodingChallenge'}, 

    {image_path: '/images/projects/motorcycle-trips.jpg', thumbnail_path: '/images/projects/thumbnails/motorcycle-trips.jpg', tags: ['MongoDB, Express.js, React.js, Node.js'], title: 'Motorcycle Trips React App', description: 'A web application with CRUD functionality. Moltorcycle riders can browse through and sign up for trips with other riders. Admin users can create, update and delete trips, riders, events as they choose. Express.js used to interact with MongoDB database. React.js calls data from Node.js server to render data.', projectUrl: './', githubUrl: 'https://github.com/wamidgette/MotorcycleRidersMERNApp'}
  ]

  export default ProjectsArray